### ISSUE TITLE
unable to find an inherited method for function ‘extract’ for signature ‘"paramedic"

### ISSUE THREAD

**Issue by chnpenny** [statdivlab/paramedic#15]
Hey dear developers,
I'm trying the example with paramedic with 'example_16S_data'. When I tried to extract the samples with rstan::extract() function, it occurred an error:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘extract’ for signature ‘"paramedic"’
I'm using the R  version 3.6.3 and the current version of paramedic from git.
Do you know what's the problem?

**Comment by bdwilliamson** [comment]
Thanks for using the package! 

Good catch -- the README was out-of-sync with the latest version of the package, so I've just updated it. The issue is that `paramedic` returns more than just `rstan` objects, so we have to specify which part of the output returned by `paramedic` to pass to, e.g., `rstan::extract`. The vignette has always been correct and shows how to use the package in a bit more detail.

**Comment by chnpenny** [comment]
Thanks! It works!
