### ISSUE TITLE
Questions about Paramedic

### ISSUE THREAD

**Issue by ChristopherBurgess-USDA** [statdivlab/paramedic#17]
I'm interested in using paramedic to compare a few different quantification techniques (qPCR, flow cytometry, etc) and seeing how they can influence downstream interpretation of our microbiome dataset. To that end I had 2 quick questions about paramedic that I couldn't find answers to in the reference material or manuscript.

1) Does paramedic take advantage of the [parallel support featured in rstan](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#loading-the-package) and would parallel support speed up computation time for this tool? 

2) What tools are appropriate to downstream analysis of paramedic output (i.e. differential abundance)? Since paramedic attempts to correct for the compositional nature of the data, I'm assuming tools such as radEmu might be inappropriate.

**Comment by bdwilliamson** [comment]
Thanks for your questions! 

1. I've just updated the "Introduction to paramedic vignette" to include an example of parallel computation, which proceeds exactly as in the `rstan` documentation you linked to. It can result in substantial speedups, depending on the number of cores you have access to.
2. A variety of downstream tools could be used to analyze paramedic output. In my view, you wouldn't pass `paramedic` output to `radEmu`, because the latter doesn't need the abundance data to be corrected (it handles this internally). Depending on how well you think `paramedic` predicted the absolute abundances, you could use these in a variety of measurement-error modeling approaches and get reasonable answers.

**Comment by adw96** [comment]
Wow, thanks, @bdwilliamson ! You beat me to it! Special thanks for implementing 1 😻 (Also, I'm so thrilled you know about `radEmu`!)

@ChristopherBurgess-USDA --- an equivalent/comparable model to `radEmu` using `paramedic`'s estimated concentrations would be a log-linear model (log \mu_ij-hat = X_i^T \beta_j, via eg a Poisson GLM). 

FWIW I've tried an analogy to this on one dataset (qPCR on subset of taxa + 16S) and see pretty good overlap between the beta's we estimate from radEmu and the beta's we get from a Poisson GLM fit to the observed (qPCR'ed) concentrations. (I compare them applying the same identifiability constraint to the the parameters estimated from the GLM).

Anything to add, David? (@ailurophilia)

@ChristopherBurgess-USDA Feel free to close if you feel we've answered your question... and thanks for your interest in our work!

**Comment by ChristopherBurgess-USDA** [comment]
@bdwilliamson Thanks for the quick answer and update to the vignette!

@adw96 Thanks for suggestion on the model family for analyzing paramedic output. Also, I heard about [radEmu from your EMBL talk](https://youtu.be/VvT3RWRdskI?si=PH2YbPu8XtQGP5yo) which convinced me to check out your lab's github :wink:!
